spring:
  application:
    name: metric-dropwizard-practice

server:
  port: 8101


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 4
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: info
