spring:
  application:
    name: metric-prometheus-practice

server:
  port: 8100


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 4
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: warn

ribbon:
  MaxConnectionsPerHost: 200 #default 50
  MaxTotalConnections: 2000 #default 200